config/routes.rb
TeeboxNetwork::Application.routes.draw do
    
  root to: "questions#index"
  
  # Errors
  match '(errors)/:status', to: 'errors#show', constraints: { status: /\d{3}/ }
  
  # Tags
  get "tagged/:tag", to: "questions#index", as: :tagged
  
  # Questions
  get "question_tags", to: "tags#question_tags", as: :question_tags #tokenInput json tags
  get "questions/unanswered", to: "questions#unanswered", as: :unanswered
  get "questions/popular", to: "questions#popular", as: :popular
  
  # Articles
  get 'admin/articles', to: 'articles#admin', as: :admin_articles

  # Users
  get "users/:id/welcome", to: "users#welcome", as: :welcome
  get "users/:id/points", to: "points#index", as: :points
  get "users/:id/questions", to: "users#questions", as: :user_questions
  get "users/:id/answers", to: "users#answers", as: :user_answers
  get "users/:id/articles", to: "users#articles", as: :user_articles
  get "/users/:id/breakdown", to: 'points#breakdown', as: :breakdown

  # Static
  get "how-it-works", to: "pages#info", as: :info
  get "sitemap", to: 'pages#sitemap', as: :sitemap
  get "about", to: 'pages#about', as: :about
  get "/terms-and-conditions", to: 'pages#terms', as: :terms
  
  devise_for :users, controllers: { confirmations: "confirmations" }, path_names: { sign_in: "login", sign_out: "logout" }
  resources :users, only: [:show, :index]
  resources :signed_urls, only: :index
  
  # Search
  get "search", to: 'search#index', as: :search
  
  # AWS End point for SNS
  post "/aws/end_point", to: 'aws_notifications#end_point', as: :end_point
  
  # Points
  resources :points, only: :index
  
  # Questions
  resources :questions do
    resources :comments, except: [:edit, :update]
    member do
      get "related"
    end
  end
  
  # Articles
  resources :articles do
    member do
       put *[:draft, :submit, :approve, :publish, :discard]
    end
    resources :comments, except: [:edit, :update]
  end
  
  # Comments
  resources :comments, except: [:edit, :update, :new, :create, :destroy, :index]
  
  # Answers
  resources :answers, except: :index do 
    member { put :correct }
    resources :comments, except: [:edit, :update]
  end
  
  # Videos
  resources :videos
  
  # Tags
  resources :tags
  
  # Notifications/Activities
  resources :activities, only: :index do
    #member { put :read }
    member { get :read }
    collection { get 'notifications' }
  end
  
  # Reports
  resources :reports, only: [:index, :new, :create, :destroy] do
    collection { get "stats" }
  end
  
  # Votes
  resources :votes, only: [:create, :new]
  
  if Rails.env.development?
    mount MailPreview => "mail_view"
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  
  attr_accessible :file, :screenshot, :job_id, :status, :name, :duration, :location
  
  has_many :questions, through: :playlists
  has_many :playlists
  belongs_to :user
  
  validates_presence_of :user_id, :file
  
  default_scope order('created_at DESC')
    
  def to_param
    "#{id} - #{File.basename(self.file)}".parameterize
  end
  
  # ========= Should be in the AWS Repo ============== 
  def aws_file_key(attribute=:file)
    self.send(attribute).gsub("http://#{CONFIG[:s3_bucket]}.s3.amazonaws.com/", '') if self.send(attribute)
  end
  
  def delete_aws_key
    folder = File.split(self.file)[0].split("/")[3..-1].join("/")
    AWS::S3.new.buckets[CONFIG[:s3_bucket]].objects.with_prefix(folder).delete_all
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  
  before_filter :authenticate_user!
  load_and_authorize_resource
  
  def show
  end
  
  def edit
  end
  
  def index
    @videos = current_user.videos
    @video = Video.new
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def new   
  end
  
  def create
    # ====== Should be in interactor ======
    @video = current_user.videos.build(params[:video])
    respond_to do |format|
      if @video.save
        TranscoderRepository.generate(@video)
        format.html { redirect_to videos_path, notice: 'Video was successfully uploaded.' }
        format.json { render json: @video, status: :created, location: @video }
        format.js 
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @video.update_attributes(video_params)
        format.html { redirect_to @video, notice: "Video updated successfully" }
        format.js
      else
        format.html { render :edit; flash[:error] = "Something went wrong. Plese try again." }
        format.js
      end
    end
  end
  
  def destroy
    # ======= Should be in an interactor ====== #
    @video = Video.destroy(params[:id])
    if @video.destroy
      @video.delete_aws_key
      respond_to do |format|
        format.html { redirect_to videos_path, notice: "Video deleted" }
        format.js
      end
    end
  end
  
  private 
  
  def video_params
    params[:video].slice(:name, :location)
  end
end

app/helpers/video_helper.rb
module VideoHelper
  
  def format_name(video, opts={})
    display_name = video.name.present? ? video.name : File.basename(video.file, '.*')
    opts[:truncate] ? truncate(display_name, length: (opts[:length] || 20)) : display_name
  end
  
  def display_video_meta_info(video, opts={})
    nbsp = '&nbsp;'.html_safe 
    capture do
      concat content_tag(:i, nbsp, class: 'icon-globe')
      concat (video.location.present? ? video.location : '--')
      concat "<br>".html_safe
      concat content_tag(:i, nbsp, class: 'icon-time')
      concat (format_seconds(video.duration) || '--')
      unless opts[:hide_date]
        concat "<br>".html_safe
        concat content_tag(:i, nbsp, class: 'icon-calendar')
        concat video.created_at.strftime("%d %b %Y")
      end
    end
  end
  
  def format_seconds(seconds)
    return nil if seconds.to_s.blank?
	  Time.at(seconds.to_i).utc.strftime("%M:%S")
  end
  
  def display_screenshot(video, size=:xl)
    if video && video.screenshot.present?
      video.screenshot
    else
      "video_screen_#{size}.png"
    end
  end
  
  def persist_selected(question, video)
    question.videos.map(&:id).include?(video.id) ? 'selected_video' : ''
  end
  
  def video_processed?(video)
    case video.status.try(:downcase)
    when "submitted"
      link_to content_tag(:i, nil, class: "icon-gear green icon-spin"), '#', class: "processing", title: "Processing, refresh to update", rel: "tooltip"
    when "error"
      link_to content_tag(:i, nil, class: "icon-exclamation-sign red"), '#', class: "processing", title: "Converting Failed", rel: "tooltip"
    end
  end
  
  def youtube_url_html5(video)
    video_tag([video], class: "sublime", size: "748x374", preload: "none", data: {"youtube-id" => strip_url(video), name: video, uid: video, autoresize: "fit"})
  end
  
  def sublime_video(video)
    video_tag([video.file], id: "video_#{video.id}", class: "sublime", size: "748x374", data: { name: video.file, uid: video.id, autoresize: "fit" }, preload: "none")
  end
  
  def strip_url(url)
    url.gsub!("http://www.youtube.com/watch?v=", "")
  end             
  
  def sublimevideo_rails
    @site_token ||= CONFIG[:sublime_token]
  end
end

app/views/videos/_failed_upload.html.erb
<div class="modal hide fade in" id="failed">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3>Upload Failed</h3>
  </div>
  <div class="modal-body">
    <p></p>
  </div>
	<div class="modal-header">
		Please view <%= link_to "Uploading Videos" %> 
	 for video best practices and guidelines</div>
  <div class="modal-footer">
    <a href="#" class="btn" data-dismiss="modal">OK</a>
  </div>
</div>

app/views/videos/_form.html.erb
<form accept-charset="UTF-8" action="http://<%= CONFIG[:s3_bucket] %>.s3.amazonaws.com" data-remote="true" class="direct-upload" enctype="multipart/form-data" method="post">
  	<%= hidden_field_tag :key %>
	<%= hidden_field_tag :AWSAccessKeyId, CONFIG[:aws_access_key_id] %>
	<%= hidden_field_tag :acl, "public-read" %>
	<%= hidden_field_tag :policy %>
	<%= hidden_field_tag :signature %>
	<%= hidden_field_tag :success_action_status, "201" %>
	<div class="fileUpload default submit">
		<span>Select File  <i class="icon-plus-sign"></i></span>
		<%= file_field_tag :file, id: "video-test-upload" %>
	</div>
</form>

<%= form_for @video, html: { multipart: true, id: "new_video" }, remote: true do |f| %>
	<% if @video.errors.any? %>
		<div id="error_explanation">
	  		<h2><%= pluralize(@video.errors.count, "error") %> prohibited this post from being saved:</h2>
	  		<ul>
	  			<% @video.errors.full_messages.each do |msg| %>
	    			<li><%= msg %></li>
	  			<% end %>
	  		</ul>
		</div>
	<% end %>
	<%= f.hidden_field :file %><br>
<% end %>

<% link_to_referral(params, 'Step 2 &nbsp;<i class="icon-circle-arrow-right"></i>', new_question_path) do |text, link| %>
	<%= link_to text, link, class: "default next" %><br>
<% end %>

app/views/videos/_playlist.html.erb
<% if videos.any? %>
	<div class="sv_playlist_table">
		<div class='sv_playlist_row sv_playlist' id="playlist1">
			<div class="sv_playlist_cell">
				<div class="col-md-8 col-sm-8 sv_column">
					<% videos.each do |video| %>
						<div class="video_wrap">
							<%= video_tag([video.file], id: "video#{video.id}", size: "748x374", 
														preload: "none", data: {autoresize: "fit"}) %>		
						</div>
					<% end %>
				</div>
				<div class="col-md-4 col-sm-4">
					<ul class="thumbnails">	
						<% videos.each do |video| %>
							<li class="row" id="thumbnail_video<%= video.id %>">
								<div class="meta-section col-md-6 col-sm-6">
									<a href="#">
										<%= image_tag(display_screenshot(video, :mini)) %>
										<span class="play" />
									</a>
								</div>
								<div class="meta-section col-md-6 col-sm-6">	
									<a class="video-thumbail-meta hidden-xs" rel="tooltip" 
										data-toggle="tooltip" title="<%= format_name(video) %>">
										<small class="white"><%= format_name(video) %></small>
									</a>
									<small class="white">
										<span class="hidden-xs"><%= display_video_meta_info(video, hide_date: true) %></span>
									</small>
								</div>	
							</li>
						<% end %>
						<% if videos.size < 3 %>
							<div class="row">
								<div class="col-md-12">
									<%= link_to raw('<i class="icon-plus-sign"></i> Add more videos'), edit_question_path(params[:id]), class: 'default-xl center full-width-btn dark-trans', data: { toggle: "tooltip" }, 
				          title: 'Add more video angles for better answers.', rel: 'tooltip' if can? :edit, videos.last %>
								</div>
							</div>
						<% end %>
						<hr style="border-top:1px solid rgba(0, 0, 0, 0.3)">
						<div class="row">
							<div class="col-md-12 center">
								<button class="btn btn-default dark-trans" id="play" data-toggle="tooltip" 
									data-state="play" title="Play/Pause">
										<i class="icon-play"></i> <i class="icon-pause"></i>
								</button>
								<div class="btn-group" role="group" aria-label="...">	
									<button class="btn btn-default dark-trans slow-mo" data-toggle="tooltip" data-speed="1"
										title="Full speed">100%</button>
									<button class="btn btn-default dark-trans slow-mo" data-toggle="tooltip" data-speed="0.5"
										title="Half speed">50%</button>
									<button class="btn btn-default dark-trans slow-mo" data-toggle="tooltip" data-speed="0.25"
										title="Quarter speed">25%</button>		
								</div>
							</div>
						</div>
					</ul>
				</div>
			</div>
		</div>		
	</div>
<% end %>		

app/views/videos/_video.html.erb
<%= content_tag(:article, id: "video_#{video.id}", class: "col-md-3 col-sm-4 col-xs-6", data: { id: video.id }) do %>
	<%= content_tag(:div, class: "video-screenshot") do %>
		<i class='icon-cog video-destroy-icon icon-spin'></i>
		<%= video_processed?(video) %>	
		<%= link_to image_tag(display_screenshot(video, :xl)), video %>
	<% end %>
	
	<h5 class="video-name"><%= link_to format_name(video), video %></h5>
	
	<%= content_tag(:p) do %>
		<%= display_video_meta_info(video) %>
		<p>
			<small><%= link_to "Delete", video_path(video), method: :delete, remote: true, id: "delete-video_#{video.id}", onclick: "$('#video_#{video.id} i.video-destroy-icon').show();", class: 'default next' %>
			<%= link_to "Edit", edit_video_path(video), class: 'default' %></small>
		</p>
	<% end %>
<% end %>

app/views/videos/_video_select.html.erb
<% if current_user.videos.any? %>
	<div id="token">
    	<% current_user.videos.each do |video| %>
	  		<article class="videos form" data-id="<%= video.id %>">
				<div id='<%= "#{video.id}_token" %>' class="selected-img">
					<%= image_tag(display_screenshot(video, :xl)) %>
					<div class="selected <%= persist_selected(question, video) %>">
						<i class="icon-ok-sign"></i>
					</div>
				</div>
					<h5 class="video-name"><%= format_name(video)  %></h5>
					<p><%= display_video_meta_info(video) %></p>															
   			</article>
    	<% end %>
	</div>
<% else %>
	<%= link_to "0 videos found. Add some videos", videos_path %><br>
<% end %>
<br>

app/views/videos/create.js.erb
<% if @video.new_record? %>
	alert("Failed to create Video: <%= j @video.errors.full_messages.join(', ').html_safe %>");
<% else %>
	var video = $("<%= j render(@video) %>").hide();
	$('#videos').prepend(video);
	video.fadeIn(1000).effect('highlight', {color: '#f7f7f7'}, 1000);
	$(".video-upload-info").html("").append("<b>Video Uploaded <i class='icon-ok-sign green'></i></b><br>").fadeIn();

	window.setTimeout(function() { 
		$("#failed").modal('hide');
	}, 1500);
	
	$(".progress").fadeOut(function() {
	  $(".progress-bar").css("width", "0%");
	});
<% end %>

app/views/videos/destroy.js.erb
$('#video_<%="#{@video.id}"%>').effect('highlight', {color: "#f7f7f7"}, 200).fadeOut();

app/views/videos/edit.html.erb
<%= content_for :head do %>
	<%= javascript_include_tag "sublime.js", defer: "defer" %>
<% end %>

<div class="row" id="video-<%= @video.id %>">
	<div class='col-md-7 col-sm-7'>
		<%= raw sublime_video(@video) %><br>		
	</div>
	<div class="col-md-5 col-sm-5" id="video-meta-info">
		<%= render partial: 'inline_form', locals: { video: @video } %>
	</div>	
</div>	

app/views/videos/edit.js.erb
var video = $(".video-meta-<%= @video.id %>");
var editFormPartial = '<%= escape_javascript(render(partial: "videos/inline_form", locals: {video: @video})) %>';

video.html(editFormPartial);

var showView = $.parseHTML('<%= escape_javascript(render template: "videos/show") %>');
var videoSidebar = $(showView).find('.video-meta-<%= @video.id %>').hide();

video.on('click', '#cancel-video-edit', function(event){
	event.preventDefault();
	video.replaceWith(videoSidebar.fadeIn());
});	

app/views/videos/index.html.erb
<% meta_title("Video library") %>

<%= render template: "videos/new" %>

<div class="row">
	<div class="col-md-12">
		<p><h4 class="video-library">Swing Videos</h4></p>
		<button class="default asphalt" onclick="VideoUpdate.request();">Refresh Videos</button>
		<hr>
	</div>
</div>
<div class="row">	
	<%= content_tag(:section, id: "videos", data: { url: videos_path }) do %>
		<%= render @videos %>
	<% end %>
</div>

<%= render partial: "shared/modals/video_upload" %>

app/views/videos/index.js.erb
var videos = $("<%= j render(@videos) %>").hide();
var videoDiv = $("#videos")
var sectionVideos = $("#videos article[id^=video]");

sectionVideos.fadeOut(250, function(){
	sectionVideos.remove();
	videoDiv.prepend(videos);
	$("#videos article[id^=video]").fadeIn(250);
});

app/views/videos/new.html.erb
<%= application_banner("video-index-banner") do %>
	<h1 class="video-upload">Step 1: Upload Videos </h1>
	<b>You can add up to 3 videos per question.<br>Max file size 12MB.</b><p></p>

	<div class=".upload-form">
		<%= render partial: "videos/form" %>
	</div>
<% end %>

app/views/videos/show.html.erb
<% meta_title(format_name @video) %>

<%= content_for :head do %>
	<%= javascript_include_tag "sublime.js", defer: "defer" %>
<% end %>

<div class='row' id="video-<%= @video.id %>">
	<div class='col-md-7 col-sm-7'>
		<%= raw sublime_video(@video) %><br>		
	</div>
	<div class="col-md-5 col-sm-5" id="video-meta-info">
		<div class="video-meta-<%= @video.id %>">
			<h5><%= format_name(@video) %></h5>
			<p><%= display_video_meta_info(@video) %></p>
		
			<%= link_to "Swing Videos", videos_path, class: "default submit" %>
			<%= link_to "Edit", edit_video_path(@video), remote: :true, class: "default" %>
			<%= link_to "Delete", video_path(@video), class: "default next", method: :delete %>
		</div>
	</div>	
</div>

app/views/videos/update.js.erb
var videoForm = $("#video-<%= @video.id %>.row");
var video = $.parseHTML('<%= escape_javascript(render template: "videos/show") %>');
var videoSidebar = $(video).find('#video-meta-info').hide();

videoForm.find('#video-meta-info').replaceWith(videoSidebar.fadeIn());