config/routes.rb
TeeboxNetwork::Application.routes.draw do
    
  root to: "questions#index"
  
  # Errors
  match '(errors)/:status', to: 'errors#show', constraints: { status: /\d{3}/ }
  
  # Tags
  get "tagged/:tag", to: "questions#index", as: :tagged
  
  # Questions
  get "question_tags", to: "tags#question_tags", as: :question_tags #tokenInput json tags
  get "questions/unanswered", to: "questions#unanswered", as: :unanswered
  get "questions/popular", to: "questions#popular", as: :popular
  
  # Articles
  get 'admin/articles', to: 'articles#admin', as: :admin_articles

  # Users
  get "users/:id/welcome", to: "users#welcome", as: :welcome
  get "users/:id/points", to: "points#index", as: :points
  get "users/:id/questions", to: "users#questions", as: :user_questions
  get "users/:id/answers", to: "users#answers", as: :user_answers
  get "users/:id/articles", to: "users#articles", as: :user_articles
  get "/users/:id/breakdown", to: 'points#breakdown', as: :breakdown

  # Static
  get "how-it-works", to: "pages#info", as: :info
  get "sitemap", to: 'pages#sitemap', as: :sitemap
  get "about", to: 'pages#about', as: :about
  get "/terms-and-conditions", to: 'pages#terms', as: :terms
  
  devise_for :users, controllers: { confirmations: "confirmations" }, path_names: { sign_in: "login", sign_out: "logout" }
  resources :users, only: [:show, :index]
  resources :signed_urls, only: :index
  
  # Search
  get "search", to: 'search#index', as: :search
  
  # AWS End point for SNS
  post "/aws/end_point", to: 'aws_notifications#end_point', as: :end_point
  
  # Points
  resources :points, only: :index
  
  # Questions
  resources :questions do
    resources :comments, except: [:edit, :update]
    member do
      get "related"
    end
  end
  
  # Articles
  resources :articles do
    member do
       put *[:draft, :submit, :approve, :publish, :discard]
    end
    resources :comments, except: [:edit, :update]
  end
  
  # Comments
  resources :comments, except: [:edit, :update, :new, :create, :destroy, :index]
  
  # Answers
  resources :answers, except: :index do 
    member { put :correct }
    resources :comments, except: [:edit, :update]
  end
  
  # Videos
  resources :videos
  
  # Tags
  resources :tags
  
  # Notifications/Activities
  resources :activities, only: :index do
    #member { put :read }
    member { get :read }
    collection { get 'notifications' }
  end
  
  # Reports
  resources :reports, only: [:index, :new, :create, :destroy] do
    collection { get "stats" }
  end
  
  # Votes
  resources :votes, only: [:create, :new]
  
  if Rails.env.development?
    mount MailPreview => "mail_view"
  end
end

app/views/shared/_article_image_select.html.erb
<div class="row">
	<div class="col-md-12">
		<p><label><i class="icon-picture"></i> Cover image</label></p>
		<p><span id="images_count">0</span> Images found<p>
	<p><small>Selected: <span id="selected_article_image">Nothing</span></small></p>
	</div>
	<div id="article_images"></div>
</div>

app/views/shared/_articles_sidebar.html.erb
<% if articles.any? %>
	<div id='articles-sidebar' class="panel panel-default">
	  <div class="panel-heading">
		<div class="panel-title text-center">
	    	<b><%= link_to 'Latest stories', articles_path, class: 'white' %></b>
		</div>	
	  </div>
	</div>
	<%= render articles, css: nil %>
<% end %>	

app/views/shared/_email_header.html.erb
<style type="text/css">
/* Have to use the style tag in an HTML page otherwise the styles predominantly get ignored by the email clients */
body,#bodyTable,#bodyCell{
	height:100% !important;
	margin:0;
	padding:0;
	width:100% !important;
	font-family: "Lucida Grande", "Lucida Sans Unicode", "Lucida Sans", Geneva, Verdana, sans-serif
}
table{
	border-collapse:collapse;
}
img,a img{
	border:0;
	outline:none;
	text-decoration:none;
}
h1,h2,h3,h4,h5,h6{
	margin:0;
	padding:0;
}
p{
	margin:1em 0;
	padding:0;
}
a{
	word-wrap:break-word;
	text-decoration: none!important;
	color: #42B0C0;
}
.ReadMsgBody{
	width:100%;
}
.ExternalClass{
	width:100%;
}
.ExternalClass,.ExternalClass p,.ExternalClass span,.ExternalClass font,.ExternalClass td,.ExternalClass div{
	line-height:100%;
}
table,td{
	mso-table-lspace:0pt;
	mso-table-rspace:0pt;
}
#outlook a{
	padding:0;
}
img{
	-ms-interpolation-mode:bicubic;
}
body,table,td,p,a,li,blockquote{
	-ms-text-size-adjust:100%;
	-webkit-text-size-adjust:100%;
}
#bodyCell{
	padding:20px;
}
.mcnImage{
	vertical-align:bottom;
}
.mcnTextContent img{
	height:auto !important;
}
body,#bodyTable{
	/*@editable*/background-color:#F2F2F2;
}
#bodyCell{
	/*@editable*/border-top:0;
}
#templateContainer{
	/*@editable*/border:0;
}
h1{
	/*@editable*/color:#606060 !important;
	display:block;
	/*@editable*/font-size:40px;
	/*@editable*/font-style:normal;
	/*@editable*/font-weight:bold;
	/*@editable*/line-height:125%;
	/*@editable*/letter-spacing:-1px;
	margin:0;
	/*@editable*/text-align:left;
}
h2{
	/*@editable*/color:#404040 !important;
	display:block;
	/*@editable*/font-size:26px;
	/*@editable*/font-style:normal;
	/*@editable*/font-weight:bold;
	/*@editable*/line-height:125%;
	/*@editable*/letter-spacing:-.75px;
	margin:0;
	/*@editable*/text-align:left;
}
h3{
	/*@editable*/color:#606060 !important;
	display:block;
	/*@editable*/font-size:18px;
	/*@editable*/font-style:normal;
	/*@editable*/font-weight:bold;
	/*@editable*/line-height:125%;
	/*@editable*/letter-spacing:-.5px;
	margin:0;
	/*@editable*/text-align:left;
}
h4{
	/*@editable*/color:#808080 !important;
	display:block;
	/*@editable*/font-size:16px;
	/*@editable*/font-style:normal;
	/*@editable*/font-weight:bold;
	/*@editable*/line-height:125%;
	/*@editable*/letter-spacing:normal;
	margin:0;
	/*@editable*/text-align:left;
}
#templatePreheader{
	/*@editable*/background-color:#FFFFFF;
	/*@editable*/border-top:0;
	/*@editable*/border-bottom:0;
}
.preheaderContainer .mcnTextContent,.preheaderContainer .mcnTextContent p{
	/*@editable*/color:#606060;
	/*@editable*/font-size:11px;
	/*@editable*/line-height:125%;
	/*@editable*/text-align:left;
}
.preheaderContainer .mcnTextContent a{
	/*@editablecolor:#606060;*/
	/*@editable*/font-weight:normal;
	/*@editable*/text-decoration:none;
}
#templateHeader{
	/*@editable*/background-color:#FFFFFF;
	/*@editable*/border-top:0;
	/*@editable*/border-bottom:0;
}
.headerContainer .mcnTextContent,.headerContainer .mcnTextContent p{
	/*@editable*/color:#606060;
	/*@editable*/font-size:14px;
	/*@editable*/line-height:150%;
	/*@editable*/text-align:left;
}
.headerContainer .mcnTextContent a{
	/*@editablecolor:#6DC6DD;*/
	/*@editable*/font-weight:normal;
	/*@editable*/text-decoration:none;
}
#templateBody{
	/*@editable*/background-color:#FFFFFF;
	/*@editable*/border-top:0;
	/*@editable*/border-bottom:0;
}
.bodyContainer .mcnTextContent,.bodyContainer .mcnTextContent p{
	/*@editable*/color:#606060;
	/*@editable*/font-size:14px;
	/*@editable*/line-height:150%;
	/*@editable*/text-align:left;
}
.bodyContainer .mcnTextContent a{
	/*@editablecolor:#6DC6DD;*/
	/*@editable*/font-weight:normal;
	/*@editable*/text-decoration:none;
}
#templateFooter{
	/*@editable*/background-color:#FFFFFF;
	/*@editable*/border-top:0;
	/*@editable*/border-bottom:0;
}
.footerContainer .mcnTextContent,.footerContainer .mcnTextContent p{
	/*@editable*/color:#606060;
	/*@editable*/font-size:11px;
	/*@editable*/line-height:125%;
	/*@editable*/text-align:left;
}
.footerContainer .mcnTextContent a{
	/*@editablecolor:#606060;*/
	/*@editable*/font-weight:normal;
	/*@editable*/text-decoration:none;
}
@media only screen and (max-width: 480px){
body,table,td,p,a,li,blockquote{
	-webkit-text-size-adjust:none !important;
}

}
@media only screen and (max-width: 480px){
body{
	width:100% !important;
	min-width:100% !important;
}
}	
@media only screen and (max-width: 480px){
td[id=bodyCell]{
	padding:10px !important;
}
}	
@media only screen and (max-width: 480px){
table[class=mcnTextContentContainer]{
	width:100% !important;
}
}	
@media only screen and (max-width: 480px){
table[class=mcnBoxedTextContentContainer]{
	width:100% !important;
}
}	
@media only screen and (max-width: 480px){
table[class=mcpreview-image-uploader]{
	width:100% !important;
	display:none !important;
}
}	
@media only screen and (max-width: 480px){
img[class=mcnImage]{
	width:100% !important;
}
}	
@media only screen and (max-width: 480px){
table[class=mcnImageGroupContentContainer]{
	width:100% !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnImageGroupContent]{
	padding:9px !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnImageGroupBlockInner]{
	padding-bottom:0 !important;
	padding-top:0 !important;
}
}	
@media only screen and (max-width: 480px){
tbody[class=mcnImageGroupBlockOuter]{
	padding-bottom:9px !important;
	padding-top:9px !important;
}
}	
@media only screen and (max-width: 480px){
table[class=mcnCaptionTopContent],table[class=mcnCaptionBottomContent]{
	width:100% !important;
}
}	
@media only screen and (max-width: 480px){
table[class=mcnCaptionLeftTextContentContainer],table[class=mcnCaptionRightTextContentContainer],table[class=mcnCaptionLeftImageContentContainer],table[class=mcnCaptionRightImageContentContainer],table[class=mcnImageCardLeftTextContentContainer],table[class=mcnImageCardRightTextContentContainer]{
	width:100% !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnImageCardLeftImageContent],td[class=mcnImageCardRightImageContent]{
	padding-right:18px !important;
	padding-left:18px !important;
	padding-bottom:0 !important;
}
}
@media only screen and (max-width: 480px){
td[class=mcnImageCardBottomImageContent]{
	padding-bottom:9px !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnImageCardTopImageContent]{
	padding-top:18px !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnImageCardLeftImageContent],td[class=mcnImageCardRightImageContent]{
	padding-right:18px !important;
	padding-left:18px !important;
	padding-bottom:0 !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnImageCardBottomImageContent]{
	padding-bottom:9px !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnImageCardTopImageContent]{
	padding-top:18px !important;
}
}	
@media only screen and (max-width: 480px){
table[class=mcnCaptionLeftContentOuter] td[class=mcnTextContent],table[class=mcnCaptionRightContentOuter] td[class=mcnTextContent]{
	padding-top:9px !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnCaptionBlockInner] table[class=mcnCaptionTopContent]:last-child td[class=mcnTextContent]{
	padding-top:18px !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnBoxedTextContentColumn]{
	padding-left:18px !important;
	padding-right:18px !important;
}
}	
@media only screen and (max-width: 480px){
td[class=mcnTextContent]{
	padding-right:18px !important;
	padding-left:18px !important;
}
}	
@media only screen and (max-width: 480px){
table[id=templateContainer],table[id=templatePreheader],table[id=templateHeader],table[id=templateBody],table[id=templateFooter]{
	max-width:600px !important;
	/*@editable*/width:100% !important;
}
}	
@media only screen and (max-width: 480px){
h1{
	/*@editable*/font-size:24px !important;
	/*@editable*/line-height:125% !important;
}
}	
@media only screen and (max-width: 480px){
h2{
	/*@editable*/font-size:20px !important;
	/*@editable*/line-height:125% !important;
}
}	
@media only screen and (max-width: 480px){
h3{
	/*@editable*/font-size:18px !important;
	/*@editable*/line-height:125% !important;
}
}	
@media only screen and (max-width: 480px){
h4{
	/*@editable*/font-size:16px !important;
	/*@editable*/line-height:125% !important;
}
}	
@media only screen and (max-width: 480px){
table[class=mcnBoxedTextContentContainer] td[class=mcnTextContent],td[class=mcnBoxedTextContentContainer] td[class=mcnTextContent] p{
	/*@editable*/font-size:14px !important;
	/*@editable*/line-height:125% !important;
}
}	
@media only screen and (max-width: 480px){
table[id=templatePreheader]{
	/*@editable*/display:block !important;
}
}	
@media only screen and (max-width: 480px){
td[class=preheaderContainer] td[class=mcnTextContent],td[class=preheaderContainer] td[class=mcnTextContent] p{
	/*@editable*/font-size:14px !important;
	/*@editable*/line-height:115% !important;
}
}	
@media only screen and (max-width: 480px){
td[class=headerContainer] td[class=mcnTextContent],td[class=headerContainer] td[class=mcnTextContent] p{
	/*@editable*/font-size:14px !important;
	/*@editable*/line-height:125% !important;
}
}	
@media only screen and (max-width: 480px){
td[class=bodyContainer] td[class=mcnTextContent],td[class=bodyContainer] td[class=mcnTextContent] p{
	/*@editable*/font-size:14px !important;
	/*@editable*/line-height:125% !important;
}
}	
@media only screen and (max-width: 480px){
td[class=footerContainer] td[class=mcnTextContent],td[class=footerContainer] td[class=mcnTextContent] p{
	/*@editable*/font-size:14px !important;
	/*@editable*/line-height:115% !important;
}
}	
@media only screen and (max-width: 480px){
td[class=footerContainer] a[class=utilityLink]{
	display:block !important;
}

}
/* Custom styles */
.default { 
	color: #fff;
	background: #31838f;
	-moz-box-sizing: border-box;
	-webkit-box-sizing: 
	border-box; box-sizing: 
	border-box; padding: 5px 10px!important; 
	border-radius:0px; 
	border:none; 
	display:inline-block; 
	text-shadow:none; 
	line-height:20px!important; 
	margin: 3px 3px 0 0; 
}
.gravatar { 
	padding: 0 10px 0px 0px; 
}
table.teebox-table { 
	vertical-align:middle; 
	margin-top: 5px; 
}
table.teebox-table td { 
	text-align:left; 
}
table.teebox-table td img { 
	max-width:50px; 
}</style>

app/views/shared/_failed_video_upload.html.erb
<div class="modal hide fade in" id="failed">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">&times;</a>
    <h3 class="video-upload">Uploading <i class="icon-cloud-upload"></i></h3>
  </div>
  <div class="modal-body">
    	<div id="dropzone">
			<div id="upload">
				<p class='video-upload-info'></p>
			</div>
			<div class="progress" id="progress">
	  			<div class="bar bar-success" style="width:0%;"></div>
			</div>
		</div>
  </div>
  <div class="modal-footer">
    <a href="#" class="default" data-dismiss="modal">OK</a>
  </div>
</div>

app/views/shared/_loading.html.erb
<div class="loading">
	<%= image_tag("spinner.gif") %>
	Loading <%= message if message %>
</div>

app/views/shared/_nav_links.html.erb
<nav id="nav_links">
	<%= link_to "Latest", root_path, class: "default #{tab_class(root_url)}" %>
	<%= link_to "Popular", popular_path, class: "default #{tab_class(popular_url)}" %>
	<%= link_to "Unanswered", unanswered_path, class: "default #{tab_class(unanswered_url)}", id: "tour-nav" %>
	<%= link_to "Stories", articles_path, class: "default  #{tab_class(articles_url)}" %>
	<%= link_to "Ask", videos_path, class: "default success question_link" %>
</nav>

app/views/shared/_promotion.html.erb
<% unless current_user %>
	<section class="promotion blue-fuzz">
		<h3>Sign up for free personalized golf tips</h3>
		<p><%= link_to "Sign up now", new_user_registration_path, class: "default-xl center full-width-btn submit" %></p>
	</section>	
<% end %>

app/views/shared/_video_select_form.html.erb
<% if current_user.videos.any? %>
	<div id="token">
    	<% current_user.videos.each do |video| %>
	  		<article class="videos form" data-id="<%= video.id %>">
				<!-- Question passed in to partial from the form template. Adds selected div -->
				<div class="selected <%= persist_selected(question, video) %>">
					<i class="icon-ok-sign" id="ok-icon"></i>
				</div>
	
				<div id='<%= "#{video.id}_token" %>' class="selected-img">
						<%= image_tag(display_xl_screenshot(video)) %>
				</div>
					<h5><%= truncate(File.basename(video.file).titleize, length: 22) %></h5>
					<small><%= video.created_at.strftime("%d/%m/%y") %></small>																
   			</article>
    	<% end %>
	</div>
<% else %>
	<%= link_to "0 videos found. Add some videos", videos_path %><br>
<% end %>
<br>

app/views/shared/carousel.html.erb
<div id="teebox-carousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#teebox-carousel" data-slide-to="0" class="active"></li>
    <li data-target="#teebox-carousel" data-slide-to="1"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><%= render template: "shared/teebox_banner" %></div>
    <div class="item"><%= render template: "shared/how_it_works" %></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#teebox-carousel" data-slide="prev"><i class='icon-chevron-left'></i></a>
  <a class="carousel-control right" href="#teebox-carousel" data-slide="next"><i class='icon-chevron-right'></i></a>
</div>

app/views/shared/teebox_banner.html.erb
<h1 class="welcome-banner">Welcome to teebox</h1>
<div id="mini-push"></div>
<section class="row">
	<div class="col-md-5 col-sm-5">
		<center>	
			<p class="banner">
				Got a hitch in your golf game?<br>Anyone can ask. Anyone can answer.<br> Everyone can progress.
			</p>
			<%= link_to "Sign Up", new_user_registration_path, class: "default next" unless current_user %>
			<%= link_to "How it works", info_path, class: "default asphalt"%>
	  	</center>
	</div>
	<div class="col-md-2 col-sm-2 hidden-xs">
		<ul class="ch-grid show">
			<li>
	        <div class="ch-item ch-img-1">
	            <div class="ch-info">
	                <h3>Swing issues?</h3>
	            </div>
				<h1><i class="icon-remove" id="banner"></i></h1>
	        </div>
	    	</li>
		</ul>
	</div>
	<div class="col-md-2 col-sm-2 hidden-xs">
		<ul class="ch-grid show">
			<li>
	        <div class="ch-item ch-img-1">
	            <div class="ch-info">
	               <h3>Ask a question</h3>
	            </div>
				<h1><i class="icon-question" id="banner"></i></h1>
	        </div>
	    	</li>
		</ul>
	</div>
	<div class="col-md-2 col-sm-2 hidden-xs">
		<ul class="ch-grid show">
			<li>
	        <div class="ch-item ch-img-1">
	            <div class="ch-info">
	                <h3>Get an answer</h3>
	            </div>
				<h1><i class="icon-ok"></i></h1>
	        </div>
	    	</li>
		</ul>
	</div>
</section>