config/routes.rb
TeeboxNetwork::Application.routes.draw do
    
  root to: "questions#index"
  
  # Errors
  match '(errors)/:status', to: 'errors#show', constraints: { status: /\d{3}/ }
  
  # Tags
  get "tagged/:tag", to: "questions#index", as: :tagged
  
  # Questions
  get "question_tags", to: "tags#question_tags", as: :question_tags #tokenInput json tags
  get "questions/unanswered", to: "questions#unanswered", as: :unanswered
  get "questions/popular", to: "questions#popular", as: :popular
  
  # Articles
  get 'admin/articles', to: 'articles#admin', as: :admin_articles

  # Users
  get "users/:id/welcome", to: "users#welcome", as: :welcome
  get "users/:id/points", to: "points#index", as: :points
  get "users/:id/questions", to: "users#questions", as: :user_questions
  get "users/:id/answers", to: "users#answers", as: :user_answers
  get "users/:id/articles", to: "users#articles", as: :user_articles
  get "/users/:id/breakdown", to: 'points#breakdown', as: :breakdown

  # Static
  get "how-it-works", to: "pages#info", as: :info
  get "sitemap", to: 'pages#sitemap', as: :sitemap
  get "about", to: 'pages#about', as: :about
  get "/terms-and-conditions", to: 'pages#terms', as: :terms
  
  devise_for :users, controllers: { confirmations: "confirmations" }, path_names: { sign_in: "login", sign_out: "logout" }
  resources :users, only: [:show, :index]
  resources :signed_urls, only: :index
  
  # Search
  get "search", to: 'search#index', as: :search
  
  # AWS End point for SNS
  post "/aws/end_point", to: 'aws_notifications#end_point', as: :end_point
  
  # Points
  resources :points, only: :index
  
  # Questions
  resources :questions do
    resources :comments, except: [:edit, :update]
    member do
      get "related"
    end
  end
  
  # Articles
  resources :articles do
    member do
       put *[:draft, :submit, :approve, :publish, :discard]
    end
    resources :comments, except: [:edit, :update]
  end
  
  # Comments
  resources :comments, except: [:edit, :update, :new, :create, :destroy, :index]
  
  # Answers
  resources :answers, except: :index do 
    member { put :correct }
    resources :comments, except: [:edit, :update]
  end
  
  # Videos
  resources :videos
  
  # Tags
  resources :tags
  
  # Notifications/Activities
  resources :activities, only: :index do
    #member { put :read }
    member { get :read }
    collection { get 'notifications' }
  end
  
  # Reports
  resources :reports, only: [:index, :new, :create, :destroy] do
    collection { get "stats" }
  end
  
  # Votes
  resources :votes, only: [:create, :new]
  
  if Rails.env.development?
    mount MailPreview => "mail_view"
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include PublicActivity::Common
  include Teebox::Toggle
  require 'obscenity/active_model'
  
  CORRECT_ANSWER = 12
  QUESTION_MARKED_AS_CORRECT = 5
  REVERT = 0
  
  attr_accessible :body, :question_id, :votes_count, :correct, :points, :comments_count
  
  belongs_to :user
  belongs_to :question, counter_cache: true
  has_many :votes, as: :votable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_one :point, as: :pointable, dependent: :destroy
  has_many :activities, class_name: "PublicActivity::Activity", as: :trackable, dependent: :destroy
   
  validates_presence_of :body, :user_id, :question_id
  validates_length_of :body, minimum: 10, maximum: 5000
  validates_uniqueness_of :correct, scope: :question_id, if: :correct?, message: "You can only have 1 correct answer per question"
  validates_uniqueness_of :user_id, scope: :question_id, message: "Only 1 answer per question per user"
  validates :body, obscenity: true
  
  before_destroy :check_correct
  
  #default_scope include: :question
  scope :by_votes, order: "votes_count DESC"
  
  def to_param
    "#{id} - #{question.title}".parameterize
  end
  
  def is_false?
    self.user == self.question.user || self.correct == false
  end
  
  def check_correct
    errors.add(:base, "You can't delete a correct answer") if self.correct == true
    errors.blank?
  end
  
  def notification_message_format
    { 
      link: self.question.try(:title), 
      text: 'answered' 
    }
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  before_filter :authenticate_user!, except: [:show]
  load_and_authorize_resource
  require 'teebox/commentable'
  include Teebox::Commentable
  
  def show
  end
  
  def create
    @answer = current_user.answers.build(params[:answer])
    respond_to do |format|
      if @answer.save
        PointRepository.create(@answer.user, @answer)
        repo = ActivityRepository.new(@answer)
        repo.generate(:create, owner: current_user, recipient: @answer.question.user)
        format.html { redirect_to @answer.question, notice: 'Answer created'}
        format.js
      else
        format.html {  redirect_to :back, notice: "Please try again" }
        format.js
      end
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to :back, notice: "Updated" }
        format.js 
        format.json { head :ok}
      else
        format.html { render "edit", notice: "Plese try again" }
        format.js
      end
    end
  end
  
  def destroy
     @answer = Answer.find(params[:id])
     @answer.destroy
     respond_to do |format|
       format.js
     end
  end
  
  def correct 
    @result = ToggleAnswerCorrect.call(params) 
    
    respond_to do |format|
      if @result.success?
        @answer = @result.answer
        format.html { redirect_to @answer.question, notice: "Success!" }
        format.js
      else
        format.html { redirect_to @answer.question, notice: @result.error }
        format.js
      end
    end
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
  def correct_answer?(answer)
    answer.correct == true ? 'green-tick' : 'default-tick'
  end
end

app/views/answers/_answer.html.erb
<article id="answer_<%= answer.id %>" class="content-box-margin">
	<div class="answer">
		<div class="answer-content">
			<%= simple_format(answer.body) %>
		</div>
		
		<div class="profile-info">	
			<%= meta_info(answer) do %>			
				<li><%= link_to raw("<i class='icon-edit-sign sm'></i>"), edit_answer_path(answer), 
					id: "edit-answer", remote: true, title: "Edit" if can? :destroy, answer %>
				<%= link_to raw("<i class='icon-remove-sign sm'></i>"), answer, 
					id: "delete-answer", remote: :true, method: :delete, 
					confirm: "Are you sure? You will lose any points associated with this answer", 
					title: "Delete" if can? :destroy, answer %><li>
			<% end %>	
		</div><!-- .profile-info -->
	</div><!-- .answer -->
	
	<div class="comments-area">
		<%= display_comments(answer) %>	
		<%= link_to "Add comment", "#" , class: "comment-button" %>
		<%= render partial: "comments/form", locals: {commentable: answer} %>
	</div>
</article>

app/views/answers/_form.html.erb
<%= form_for @answer, remote: true do |f| %>

	<% if @answer.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@answer.errors.count, "error") %> prohibited this post from being saved:</h2>

			<ul>
				<% @answer.errors.full_messages.each do |msg| %>
  					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	
	<%= f.hidden_field :question_id, value: question_id %>

	<div class="field">
		<%= f.text_area :body, id: "answer-form-#{@answer.object_id}", placeholder: "try to be as objective as possible"  %>
		<script type="text/javascript">
		  $('#answer-form-<%= @answer.object_id %>').wysihtml5(
			WysihtmlEditorOptions.answer
		  );
		</script>
	</div>
	
	<%= f.submit "Save Answer", class: "default success" %>
	<%= link_to "Cancel", "#", class: "default cancel-answer" if controller.action_name == "edit" %>
<% end %>
<hr>

app/views/answers/correct.js.erb
<% if @answer.errors.any? || @result.error %>
	alert("<%= j @result.error.html_safe %>");
<% else %>
	var answer = $('.correct_<%= @answer.id %>').closest("li");
	<% if @answer.correct == true %>
		answer.addClass("green-tick");
	<% else %>
		answer.removeClass("green-tick");
	<% end %>
	$('.user_<%= @answer.user.id %>').text("<%= @answer.point.user.reputation %>");
	$('.user_<%= @answer.question.user.id %>').text("<%= @answer.question.point.user.reputation %>");
<% end %>

app/views/answers/create.js.erb
<% if @answer.new_record? %>
	alert("<%= j @answer.errors.full_messages.join(', ').html_safe %>");
<% else %>
	var answer = $("<%= j render(@answer) %>").hide();
	$('#question-answers').append(answer);
	answer.fadeIn(1000).effect('highlight', {color: '#f7f7f7'}, 1000);
	$('#new_answer').hide();
	$('.new_comment').hide();
	$('#answer-button').text("Answer Question");
	$('.wysihtml5-sandbox').contents().find('body').html('');
	$('#answers-count h3').text("<%= pluralize(@answer.question.answers_count + 1, 'Answer') %>");
	$('#answers-count').addClass("answered");
<% end %>

app/views/answers/destroy.js.erb
<% unless @answer.errors.blank? %>
	alert("<%= j @answer.errors.full_messages.join(', ').html_safe %>");
<% else %>
	$('#answer_<%="#{@answer.id}"%>').effect('highlight', {color: "#f7f7f7"}, 200).fadeOut();
	$('#answers-count h3').text("<%= pluralize(@answer.question.answers_count - 1, 'Answer') %>");
	<% if @answer.question.answers_count <= 1 %>	
		$('#answers-count').removeClass("answered");
		$('#answers-count').addClass("unanswered");
	<% end %>
	$('.user_<%= @answer.user.id %>').text("<%= @answer.point.user.reputation %>");
<% end %>

app/views/answers/edit.js.erb
var answer = $("#answer_<%= @answer.id %>");
var editFormPartial = '<%= escape_javascript(render(partial: "answers/form", locals: {question_id: @answer.question_id}))%>';

answer.find(".answer").css("background","#fff");
answer.find(".answer").html(editFormPartial);

// Cancel button disguards changes and re-renders the @answer template
answer.on("click", ".cancel-answer ", function(event) {
	event.preventDefault();
	answer.replaceWith("<%= escape_javascript(render @answer) %>");
	$(".new_comment").hide();
});

app/views/answers/show.html.erb
<% meta_title("Answer: #{@answer.question.title}") %>
<% meta_keywords(@answer.question.tags.map(&:name).join(", ")) %>
<% meta_description(@answer.question.title) %>

<body class="teebox-xl">
	<div class="center-block">
		<div class="col-md-8 col-md-offset-2 clearfix">
			<%= render @answer %>
			<%= link_to @answer.question, class: "default submit" do %>
				<i class="icon-hand-left white"></i>
				<%= @answer.question.title %>
			<% end %>	
		</div>
	</div>
</body>	

app/views/answers/update.js.erb
<% if @answer.errors.any? %>
  	alert("Failed to edit answer: <%= j @answer.errors.full_messages.join(', ').html_safe %>");
<% else %>
  	$('#answer_<%="#{@answer.id}"%>').replaceWith('<%= j render(@answer) %>');
	$('#answer_<%="#{@answer.id}"%>').effect('highlight', {color: '#f7f7f7'}, 1000);
	$('.new_comment').hide();
<% end %>