config/routes.rb
TeeboxNetwork::Application.routes.draw do
    
  root to: "questions#index"
  
  # Errors
  match '(errors)/:status', to: 'errors#show', constraints: { status: /\d{3}/ }
  
  # Tags
  get "tagged/:tag", to: "questions#index", as: :tagged
  
  # Questions
  get "question_tags", to: "tags#question_tags", as: :question_tags #tokenInput json tags
  get "questions/unanswered", to: "questions#unanswered", as: :unanswered
  get "questions/popular", to: "questions#popular", as: :popular
  
  # Articles
  get 'admin/articles', to: 'articles#admin', as: :admin_articles

  # Users
  get "users/:id/welcome", to: "users#welcome", as: :welcome
  get "users/:id/points", to: "points#index", as: :points
  get "users/:id/questions", to: "users#questions", as: :user_questions
  get "users/:id/answers", to: "users#answers", as: :user_answers
  get "users/:id/articles", to: "users#articles", as: :user_articles
  get "/users/:id/breakdown", to: 'points#breakdown', as: :breakdown

  # Static
  get "how-it-works", to: "pages#info", as: :info
  get "sitemap", to: 'pages#sitemap', as: :sitemap
  get "about", to: 'pages#about', as: :about
  get "/terms-and-conditions", to: 'pages#terms', as: :terms
  
  devise_for :users, controllers: { confirmations: "confirmations" }, path_names: { sign_in: "login", sign_out: "logout" }
  resources :users, only: [:show, :index]
  resources :signed_urls, only: :index
  
  # Search
  get "search", to: 'search#index', as: :search
  
  # AWS End point for SNS
  post "/aws/end_point", to: 'aws_notifications#end_point', as: :end_point
  
  # Points
  resources :points, only: :index
  
  # Questions
  resources :questions do
    resources :comments, except: [:edit, :update]
    member do
      get "related"
    end
  end
  
  # Articles
  resources :articles do
    member do
       put *[:draft, :submit, :approve, :publish, :discard]
    end
    resources :comments, except: [:edit, :update]
  end
  
  # Comments
  resources :comments, except: [:edit, :update, :new, :create, :destroy, :index]
  
  # Answers
  resources :answers, except: :index do 
    member { put :correct }
    resources :comments, except: [:edit, :update]
  end
  
  # Videos
  resources :videos
  
  # Tags
  resources :tags
  
  # Notifications/Activities
  resources :activities, only: :index do
    #member { put :read }
    member { get :read }
    collection { get 'notifications' }
  end
  
  # Reports
  resources :reports, only: [:index, :new, :create, :destroy] do
    collection { get "stats" }
  end
  
  # Votes
  resources :votes, only: [:create, :new]
  
  if Rails.env.development?
    mount MailPreview => "mail_view"
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  require 'obscenity/active_model'
  
  attr_accessible :name, :explanation, :updated_by, :user_id
  has_many :taggings
  has_many :questions, through: :taggings
  validates :name, presence: true, uniqueness: true, length: { maximum: 100, minimum: 2}
  
  validates :name, obscenity: true #{sanitize: true, replacement: "[censored]"} 
  validates :explanation, obscenity: true #{sanitize: true, replacement: "[censored]"} 
  
  after_initialize :init
  
  include PgSearch
  pg_search_scope :search,  against: [:name, :explanation], using: { tsearch: { prefix: true, dictionary: "english", any_word: true } }
                            
  def init
    self.explanation ||= "no explanation"
  end                          
  
  def self.text_search(query)
    if query.present?
      search(sanitize(query))
    else
      scoped
    end
  end
  
  def self.cloud
    self.joins(:taggings).select('tags.*, count(tag_id) as "tag_count"').group("tags.id").order('tag_count desc')
  end
  
  def self.tokens(query)
    tags = where("name ilike ?", "%#{query}%")
    if tags.empty?
      [{id: "<<<#{query}>>>", name: "New: \"#{query}\""}]
    else
      tags
    end
  end

  def self.ids_from_tokens(tokens) 
    tokens.gsub!(/<<<(.+?)>>>/) { create!(name: $1).id }
    tokens.split(',')
    rescue
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  before_filter :authenticate_user!, except: :index
  load_and_authorize_resource
  
  def new
    @tag = Tag.new
  end
  
  def show
    @tag = Tag.find(params[:id])
  end
  
  def index
    @tag = Tag.new
    @tags = Tag.order("name").paginate(page: params[:page], per_page: 21).text_search(params[:search])
  end
  
  def create
    @tag = Tag.create(params[:tag])
    if @tag.save
      redirect_to tags_path, notice: "Tag created" 
    else
      render :new, notice: "Try again" 
    end
  end
  
  def update
    @tag = Tag.find(params[:id])
    @tag.user_id, @tag.updated_by = current_user.id, current_user.username
    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html {  redirect_to tags_path, notice: "Tag updated" }
        format.json { head :no_content }
      else
        format.html { render :edit, notice: "Try again"  }
        format.json { render json: @tag.errors, status: :unprocessable_entity  }
      end
    end
  end
  
  def edit
    @tag = Tag.find(params[:id])
  end
  
  def destroy
    @tag = Tag.find(params[:id]).destroy
    redirect_to tags_path, notice: "Tag Deleted"
  end
  
  def question_tags
    @tags = Tag.order(:name)
    respond_to do |format|
      format.json { render json: @tags.tokens(params[:q]) }
    end
  end
end

app/helpers/tag_helper.rb
module TagHelper
  
  def tag_class(tag)
    current_page?(tagged_url(tag.name)) ? "current_tag" : "tag" 
  end
  
  def tab_class(url)
    current_page?(url) ? "submit" : "asphalt" 
  end
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
	<% if @tag.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@tag.errors.count, "error") %> prohibited this post from being saved:</h2>

			<ul>
				<% @tag.errors.full_messages.each do |msg| %>
		  		<li><%= msg %></li>
					<% end %>
			</ul>
		</div>
	<% end %>
	
	<div class="field">
		<%= f.label :name, raw('<i class="icon-align-justify"></i> Name') %>
		<%= f.text_field :name, placeholder: "Spine Angle, Chipping etc" %>
	</div><br>

	<div class="field">
		<%= f.label :explanation, raw('<i class="icon-info-sign"></i> Explanation') %>
		<%= f.text_area :explanation, placeholder: "Try and be as concise as possible",size: "30x4" %>
	</div><br>
	
	<p><%= f.submit "Save Tag", class: "default submit" %></p>
	<%= link_to "Back to Tag Vault", tags_path %>
<% end %>

app/views/tags/_tag.html.erb
<div class="tag-box col-md-12">
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title">
	    	<%= link_to tag.name, tagged_path(tag.name) %>
	    </h3>
	  </div>
	  <div class="panel-body">
	   	<p><%= tag.explanation %><br>
		<small>
			updated <%= time_ago_in_words(tag.updated_at) %> ago
			<%= link_to "Delete", tag, method: :delete if can? :destroy, tag %>
			<%= link_to "Edit", edit_tag_path(tag) if can? :edit, tag %>
		</small></p>
	  </div>
	</div>
</div>	

app/views/tags/_tag_cloud.html.erb
<div class="row">
	<div id="tag_cloud" class="col-md-12">
		<% questions.each do |tag| %>
			<div class="tag_cloud_tag">
				<%= link_to "#{tag.name} x #{tag.tag_count}", tagged_path(tag.name), class:  tag_class(tag) %>
			</div>
		<% end %>
		<div class="tag_cloud_tag">
			<%= link_to "View all Tags", tags_path, class: "tag" %>
		</div>	
	</div>
</div>
<!--<div id="tiny-push"></div>-->

app/views/tags/edit.html.erb
<% meta_title("Edit: #{@tag.name}") %>

<h1>Editing: <%= @tag.name %></h1>
<%= render partial: "tags/form" %>

app/views/tags/index.html.erb
<% meta_title("Tag Vault") %>

<%= application_banner("blue-fuzz-banner") do %>
	<h1 class="ranking">Tag Vault&nbsp; <i class="icon-tags"></i></h1>	
	<p>A tag is a word or phrase that categorizes your question with other, similar questions, making it easier for others to find and answer your question.</p>
	<%= form_tag tags_path, id: "tag-search", method: "get" do %>
		<%= text_field_tag :search, params[:search], class: 'form-control', id: "search-tags", placeholder: "Search for tags" %>
	<% end %>
	<%= link_to "Create a new Tag", new_tag_path, class: "default submit" if can? :create, Tag %>
<% end %>

<%= display_results(@tags, text: params[:search]) if params[:search] %>

<section id="tags" class="row">
	<%= render @tags %>
</section>
	
<div class="text-center">
	<%= will_paginate @tags %>
</div>

<p><small>Credit to the PGA of America. <%= link_to "Source", "http://www.pga.com/golf-instruction/instruction-feature/fundamentals/golf-glossary", target: "_blank" %></small></p>

app/views/tags/new.html.erb
<% meta_title("Create tag") %>

<h1>Create a new Tag</h1>
<p>Tags are a way to help organize our questions. When creating a new tag please make sure they are as concise as possible.</p>
<br>

<div id="tag_form">
	<%= render partial: "tags/form" %>
</div>

app/views/tags/show.html.erb
<% meta_title(@tag.name.titleize) %>

<%= render @tag %><br>
<%= link_to "Tag Vault", tags_path, class: "default" %>